### ISSUE TITLE
Error - cannot find the path specified

### ISSUE THREAD

**Issue by Respoda** [alphaonex86/Ultracopier#39]
Hi, ever since I updated the application to this latest version, everytime I cut/paste folders I'm getting error "cannot find file specified" and files inside the folders are not copied over...it creates the folders but cannot find the files inside them and I have to either skip them or cancel the entire operation. 

This was never an issue with the previous version (1.8.something). This version apparently has a broken 'cut' paste functionality.

Pls fix...and pls point me to the installer for 1.8.xx so that I can downgrade.

Thank you.

**Comment by alphaonex86** [comment]
Hi, No version 1.8, maybe it's the version 1.6?: http://files.first-world.info/ultracopier/1.6.1.5/ultracopier-windows-x86-1.6.1.5-setup.exe
http://files.first-world.info/ultracopier/1.6.1.5/ultracopier-windows-x86_64-1.6.1.5-setup.exe

**Comment by Respoda** [comment]
yes, 1.6 thanks

**Comment by Respoda** [comment]
So you're not even fixing it? Cool...

**Comment by alphaonex86** [comment]
All should be fixed into version 2. The remain bug is out of scope and internal to windows,

**Comment by Respoda** [comment]
Well, it clearly isnt fixed. Something that worked in a previous version no longer works now, that is a broken feature, and since nothing changes in my windows os it is not internal to windows at all. If it was due to windows then 1.6 would have the same issue. Something broke through the changes you made in the updated version of your software. You're trying to get off easy which already shows the commitment. Thanks anyway then. Be lazy. Kind regards.



Sent from my Samsung Galaxy smartphone.


-------- Original message --------

**Comment by alphaonex86** [comment]
The different is version 1 manipulate file via Qt (linked to various bug), now via native API.
How reproduce this?

To send me a debug report:
- Stop the old installed version
- Uninstall it
- reboot
- download http://files.first-world.info/ultracopier/2.0.4.8/ultracopier-debug-windows-x86-2.0.4.8.zip
- decompress and start this version
- Do your bug
- right click on systray icon (near the clock)
- save the debug report

**Comment by Respoda** [comment]
OK ! That's what I'm talking about !

But this version doesn't work at all, I get following message : 

"Pipe name" user name: xxxx pipe name: \\.\advanced-copier-42006c006xxxxxxxxxxxxxx"

application does nothing. Perhaps because this is x86 and I use x64 windows ?
I think you need to give me x64 debug ? thanks.

**Comment by alphaonex86** [comment]
This is just a debug message, validate it.
You can start manual copy too.

**Comment by Respoda** [comment]
it works after clicking ok :)

I could perfectly reproduce this bug.
See log file ;)

I copied a few folders with large video files. All got same error of 'could not find file specified'.


[ultracopier-bug-report.log.zip](https://github.com/alphaonex86/Ultracopier/files/3828640/ultracopier-bug-report.log.zip)

**Comment by Respoda** [comment]
For now I will use 1.6 then. Glad you are looking into this.

**Comment by Respoda** [comment]
ok so now each time I reboot I get a note about ultracopier debug application and have to cancel it running. What do i still have to remove here? I have no ultracopier installed anymore...

**Comment by Respoda** [comment]
appdata/local/temp still has files active that try to run it after reboot

**Comment by Respoda** [comment]
messy ! :/

**Comment by alphaonex86** [comment]
Remove ultracopier.exe, reboot, remove all the folder. Install

**Comment by alphaonex86** [comment]
Hi, What kind is G: ? G: is not accessible from the current user. Maybe right problem.

**Comment by Respoda** [comment]
I checked and it is accessible. I am full allowed on that drive security. But i am admin user and perhaps that is issue for uc ...only the uc app cannot access drive. And still, it DOES copy the folders and also when copying instead of cutting all goes perfect on drive g...



Sent from my Samsung Galaxy smartphone.


-------- Original message --------

**Comment by alphaonex86** [comment]
Yes, some use have repported when UC is started as admin or the current user is admin.
I continue search what can happen on my side on move.

**Comment by Respoda** [comment]
Ok. Thank you.


Sent from my Samsung Galaxy smartphone.


-------- Original message --------

**Comment by Respoda** [comment]
Hi, is this fixed in version 2.2 that is now released ? thanks ...

**Comment by alphaonex86** [comment]
No, seam problem of Windows, Windows list the folder but when I try access it say:
cannot find the path specified
Then I don't have solution for now.

**Comment by Respoda** [comment]
So I'm stuck with 1.6 ... :(

**Comment by alphaonex86** [comment]
Give a try to version 2

**Comment by Befbo** [comment]
This seems to still not be fixed. Is this being updated anymore?

**Comment by alphaonex86** [comment]
Then I will check this again

**Comment by alphaonex86** [comment]
http://ultracopier.first-world.info/temp/ultracopier-windows-x86-2.2.4.11.zip
This version fix your problem?

**Comment by Respoda** [comment]
that version crashes, doesn't work at all. I need stable version for win7 x64 xp1

**Comment by alphaonex86** [comment]
This version is stable here, bug or crash? because crash can only be fixed by compiling and use a debugger

**Comment by Respoda** [comment]
It crashes immediately when starting. Also, a DOS window opens when starting, which (i believe) should not happen.

![crash](https://user-images.githubusercontent.com/49797223/124162440-b9b0ed00-da9e-11eb-8158-3153b94f91ff.PNG)

**Comment by Respoda** [comment]
I've always used version 1.6 because of the issues described here in this thread. So the issue is still not fixed after more than a year. Will it ever? Because this software is supposed to be very useful in combination with win7. 

Win10 already has a decent copy system, but windows 7 does NOT. So you really should focus on win7 now, so that it finally works.

**Comment by alphaonex86** [comment]
You can click on yes and save the debug report and send me. On all my configuration tested (from windows XP to windows 11), all is working, then I don't understand the problem.

When I can reproduce or understand the problem, all will be fixed quickly.
You can download https://www.qt.io/download-open-source qt install it, compile ultracopier from source, start into debug mode, skip the debug report, it will crash and generate a backtrace (where have the problem, bottom part of the IDE), copy to clip board, paste here

**Comment by Respoda** [comment]
Can you link me directly to the right one on that website cause I'm not finding anything to download on that page.

**Comment by Respoda** [comment]
Huh...now I start it to send the report and it does NOT crash now, but hangs on this :

![screen456](https://user-images.githubusercontent.com/49797223/124178327-b96e1d00-dab1-11eb-814b-a7e40ce068f1.PNG)

**Comment by Respoda** [comment]
Aaaand now it DID crash when closing and starting again. Here is the report: [ultracopier-bug-report.log.zip](https://github.com/alphaonex86/Ultracopier/files/6750331/ultracopier-bug-report.log.zip)

**Comment by alphaonex86** [comment]
When to console is open, you don't have system tray icon near the clock?
You should not close the console.

This link can help you: https://www.youtube.com/watch?v=rjpVsooMaQo

**Comment by Respoda** [comment]
I do have it in systray, but in v1.6 there is no console. I do not want an open console window because I have ultracopier open in systray all the time. It starts with windows and is to replace the explorer standard copy. I can't have that console open all the time; can't you make it that it is at least hidden please? 

And still, I get message that ultracopier crashed, every time I start windows (and open the program).

**Comment by Respoda** [comment]
Something is now wrong with my explorer. every time I copy or cut and paste something, I get this error, then another screen saying cannot find path specified, and then it just copies or pastes whatever was asked. I never got these errors before I tried this new version of ultracopy. Mind you, ultracopy is NOT activated, this is with the default explorer copy function. I believe these errors are related to ultracopier though.

![screen000](https://user-images.githubusercontent.com/49797223/124190202-29849f00-dac2-11eb-8b75-360b41cb4b10.PNG)

**Comment by alphaonex86** [comment]
> I do have it in systray, but in v1.6 there is no console. I do not want an open console window because I have ultracopier open in systray all the time. It starts with windows and is to replace the explorer standard copy. I can't have that console open all the time; can't you make it that it is at least hidden please?
> 
> And still, I get message that ultracopier crashed, every time I start windows (and open the program).

This is only in version debug to get the needed info. The normal version https://cdn.confiared.com/files.first-world.info/ultracopier/2.2.4.11/ultracopier-windows-x86_64-2.2.4.11-setup.exe don't have this. You can use the normal version and delete the debug version, reboot to have normal use.

**Comment by Respoda** [comment]
Ah...that explains a lot. I was using a debug version without knowing. I installed the normal version and no crash yet. I tried a few copies and all ok. I will test it for a few days but this looks promising.

**Comment by Respoda** [comment]
Everything seems to work fine now with this version. I'll keep testing today, but it seems all is good now. Thank you very much. I will buy the ultimate version tonight. <3
